//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string ShortDescription { get; set; }
        public int TotalPointsScored { get; set; }
        public int GameID { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
